@call bcomp bluebeep
@pause
@call ed bbp_vars
@call bcomp bluebeep
@exe\sostool a exe\bluebeep.exe %exesize onkeld.key
@exe\sostool a exe\bluebeep.exe %exesize bosskey.scr
@exe\sostool a exe\bluebeep.exe %exesize *.voc
@exe\sostool a exe\bluebeep.exe %exesize ct-voice.drv
@exe\sostool a exe\bluebeep.exe %exesize bluebeep.doc
@exe\sostool a exe\bluebeep.exe %exesize bluebeep.wls
@exe\sostool a exe\bluebeep.exe %exesize bluebeep.ccd
@exe\sostool a exe\bluebeep.exe %exesize bluebeep.set
@exe\sostool a exe\bluebeep.exe %exesize bluebeep.dtl
@unset exesize
